name: "Workflow to build Java project"

on:
  push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout codebase"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: "Get SemVer" 
        uses: zwaldowski/semver-release-action@v3
        id: sem_ver
        with:
          bump: "patch"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
     
      - name: "Set up JDK 17"
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      
      - name: "Build with Maven"
        run: mvn -ntp clean package
      
      - name: "Build Docker image"
        uses: docker/build-push-action@v4
        with:
          tags: ${{ github.action_repository }}:${{ steps.sem_ver.outputs.version }}
          context: ${{ github.workspace }}
      
      - name: "Create GitHub release"
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.sem_ver.outputs.version }}
          token: ${{ github.token }}
